### PR TITLE
Added electra to list of models for cls and lm

### PR DESCRIPTION
**Pull request by lingdoc**
Not sure if this conflicts with commit e9976584dfe39f3606ff28f1294595e30c2b22e1.

### CODE REVIEW

**Comment by kaushaltrivedi** [comment]
Yes it will conflict with using Electra for sequence classification. Can you get the latest changes and submit again.

**Comment by lingdoc** [comment]
Ok, rebased. From what I can tell, in e9976584dfe39f3606ff28f1294595e30c2b22e1 `ElectraConfig` is imported from Transformers in `learner_cls.py` and the following lines of code are added:
https://github.com/kaushaltrivedi/fast-bert/blob/7b1bac2cba9a6203a640f197a23e0fac8dbe2e5e/fast_bert/learner_cls.py#L158-L166
My code removes lines 158-165 but adds the following imports, in line with the other models:
https://github.com/lingdoc/fast-bert/blob/f3034681442c8e943935ec1b9b06e987a7206c3f/fast_bert/learner_cls.py#L53-L56
So it seems like for the basic `ElectraForSequenceClassification` class it's just preference whether you want the version in line with the other imports, or whether you prefer an extra if/else statement.

But I think my version of `learner_cls.py` is required for the code I introduce in `modeling.py` to allow an `ElectraForMultilabelSequenceClassification` class.

The additional code in `learner_lm.py` just enables Electra to be used for language modeling.

**Comment by lingdoc** [comment]
I should add that to use the new `ElectraForSequenceClassification` from Transformers, you need to upgrade to Transformers 2.10.0 or greater, and that then your fast tokenizers might not work (see #222). So maybe we should wait until that bug is fixed before merging..?

**Comment by kaushaltrivedi** [comment]
ok. lets wait then.

**Comment by lingdoc** [comment]
Okay, finally updated and rebased. Should be good for merge, as #222 is resolved.

**Comment by kaushaltrivedi** [comment]
merged

**Pull request merged**
